#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_4x4(KC_P7, KC_P8, KC_P9, KC_PSLS, KC_P4, KC_P5, KC_P6, KC_PAST, KC_P1, KC_P2, KC_P3, KC_PMNS, MO(1), KC_P0, KC_ENT, KC_PPLS),
	[1] = LAYOUT_ortho_4x4(DF(2), RGB_TOG, RGB_RMOD, RGB_MOD, KC_VOLD, KC_VOLU, RGB_HUD, RGB_HUI, RGB_SPD, RGB_SPI, RGB_SAD, RGB_SAI, KC_TRNS, KC_BSPC, RGB_VAD, RGB_VAI),
	[2] = LAYOUT_ortho_4x4(KC_TRNS, KC_Q, KC_W, KC_E, KC_TAB, KC_A, KC_S, KC_D, KC_LSFT, KC_NO, KC_NO, KC_R, KC_LCTL, DF(0), MO(3), KC_SPC),
	[3] = LAYOUT_ortho_4x4(KC_ESC, KC_1, KC_2, KC_3, KC_NO, KC_NO, KC_NO, KC_4, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO),
	[4] = LAYOUT_ortho_4x4(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};
